<?php

namespace Site\ParnalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceRepository extends EntityRepository
{
    
  public function findbetweendate(\Datetime $date1)
   {
       $queryBuilder = $this->createQueryBuilder('a');
       $queryBuilder->where('a.fin >= :date1 ')
                ->setParameter('date1', $date1->format('Y-m-d H:i:s')); 
       $queryBuilder->andWhere('a.debut <= :date1 ')
                ->setParameter('date1', $date1->format('Y-m-d H:i:s')); 
       $queryBuilder->orderBy('a.debut','ASC');

       return $queryBuilder->getQuery()
                           ->getResult();
   } 
}