<?php

namespace Site\ParnalBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Site\ParnalBundle\Entity\Seance;

/**
 * DebatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CineDebatRepository extends SeanceRepository
{
}