<?php

namespace Site\ParnalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FilmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilmRepository extends EntityRepository
{
    public function findLesRealisateurs($real)
    {
        $queryBuilder = $this->createQueryBuilder('f'); 	 
        $queryBuilder->select('DISTINCT f.realisateur');
        $queryBuilder->where($queryBuilder->expr()->like('f.realisateur', "'".$real."%'"));
         $queryBuilder->orderBy('f.realisateur','ASC'); 
        $query = $queryBuilder->getQuery(); 		 	  
        return $query->getResult(); 	
    }
    
    public function findActif($valactif)
    {
      $queryBuilder = $this->createQueryBuilder('f'); 	 
      $queryBuilder->where('f.actif = :valactif')
                   ->setParameter('valactif', $valactif)
                   ->orderBy('f.titre','ASC'); 
      $query = $queryBuilder->getQuery(); 		 	  
      return $query->getResult();        
    }
    
    public function findAlltrie()
    {
      $queryBuilder = $this->createQueryBuilder('f') 	 
                   ->orderBy('f.titre','ASC'); 
      $query = $queryBuilder->getQuery(); 		 	  
      return $query->getResult();        
    }
    
    public function findNclasse()
    {
      $queryBuilder = $this->createQueryBuilder('f'); 	 
      $queryBuilder->where('f.artessai = 0')
                   ->orderBy('f.titre','ASC'); 
      $query = $queryBuilder->getQuery(); 		 	  
      return $query->getResult();        
    }
    
}