<?php

namespace Site\ParnalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends EntityRepository
{
    public function lesimagesdufilm($id)
    {
      $queryBuilder = $this->createQueryBuilder('i')
                     ->innerJoin('i.lefilm', 'f')
                     ->addSelect('f.id')
                     ->where('i.lefilm = :id ')
                     ->setParameter('id', $id);

              
       return $queryBuilder->getQuery()
                           ->getArrayResult();
    }
}