<?php

namespace Site\ParnalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MultiEvRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MultiEvRepository extends EntityRepository
{
}