<?php

namespace Site\ParnalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProgrammeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgrammeRepository extends EntityRepository
{
 public function recupvalide() {
   $datejour = new \DateTime();
   $queryBuilder = $this->createQueryBuilder('p');
   $queryBuilder->where('p.finaffichage >= :date1 ')
                ->setParameter('date1', $datejour->format('Y-m-d H:i:s'))
                ->orderBy('p.finaffichage','ASC');
              
   return $queryBuilder->getQuery()
                       ->getArrayResult(); 
}
}